apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-config
  namespace: healthcare
data:
  app-config.conf: |
    APP_ENV=production
    DB_HOST=mysql-service.healthcare.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: healthcare
type: Opaque
data:
  DB_PASSWORD: SGVhbHRoQ2FyZUAxMjM=
  JWT_SECRET: c3VwZXJzZWNyZXRqd3RrZXkxMjM=
