apiVersion: v1
kind: PersistentVolume
metadata:
  name: healthcare-pv-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/health-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: healthcare-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/health-1"
