apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthcare-sa
  namespace: healthcare
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: healthcare
  name: healthcare-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: healthcare-rb
  namespace: healthcare
subjects:
- kind: ServiceAccount
  name: healthcare-sa
  namespace: healthcare
roleRef:
  kind: Role
  name: healthcare-role
  apiGroup: rbac.authorization.k8s.io
